language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t tommyshere2/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true tommyshere2/react-test npm test

after_success:
  - docker build -t tommyshere2/multi-client ./client
  - docker build -t tommyshere2/multi-nginx ./nginx
  - docker build -t tommyshere2/multi-server ./server
  - docker build -t tommyshere2/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images to dockerhub
  - docker push tommyshere2/multi-client
  - docker push tommyshere2/multi-nginx
  - docker push tommyshere2/multi-server
  - docker push tommyshere2/multi-worker
