language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t tommylee/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true tommylee/react-test npm test

after_success:
  - docker build -t tommylee/multi-client ./client
  - docker build -t tommylee/multi-nginx ./nginx
  - docker build -t tommylee/multi-server ./server
  - docker build -t tommylee/multi-worker ./worker

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push images to dockerhub
  - docker push tommylee/multi-client
  - docker push tommylee/multi-nginx
  - docker push tommylee/multi-server
  - docker push tommylee/multi-worker
